S1 = subset(kidney, idents=c("PEC","Podo"))
S1 = FindVariableFeatures(S1, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
S1 = ScaleData(S1, features=rownames(S1))
S1 = RunPCA(S1, npcs=30, verbose=T)
S1 = RunUMAP(S1,  dims=1:20)
S1 = FindNeighbors(S1,  dims=1:20)
S1 = FindClusters(S1, resolution = 1)
marker <- FindAllMarkers(S1, min.diff.pct = 0.3 , only.pos = TRUE)
